update

diff --git a/runit b/runit
--- a/runit
+++ b/runit
@@ -1,69 +1,60 @@
 #!/bin/bash
 
-PROCFILE="Profile"
+PROCFILE="Procfile"
 ENV_FILE=".env"
-
-PORT=8080
-DATE_FORMAT="+%Y-%m-%d|%H:%M:%S"
 
 PROCESS_NAME=()
 PROCESS_COMMAND=()
+
+PORT=8080
+DATE_FORMAT="+%Y-%m-%d|%H:%M:%S"
 
 GREEN="\033[32m"
 YELLOW="\033[33m"
 BLUE="\033[34m"
 COLOR="\033[0m"
 
+isCheck=0
+
 trap 'handle_signal' SIGINT
 trap 'handle_signal' SIGTERM
+
 
 #参数输入提示
 function usage() {
 	echo "Usage: runit [-c] [-f procfile|Procfile] [-e envfile|.env]"
 }
 
-#对输入的参数进行检验
-function verify() {
-	if [[ $# == 0 ]]
-	then
-		run_command
-		wait
-	else
-		while [ $1 ]
+#对输入参数进行检验
+function verify(){
+	while [ $1 ]
 		do
 			if [[ $1 == "-c" ]]
 			then
-				echo "dd"
+				isCheck=1
 
 			elif [[ $1 == "-h" ]]
 			then
 				usage
+				exit 1
+
 			elif [[ $1 == "-e" ]]
 			then
 				shift
 				if [[ -n $1 && $1 != \-* ]]
 				then
 					ENV_FILE=$1
-					load_env_file
-					if [[ $? != 0 ]]
-                    then
-                        exit 1
-                    fi
 				else
 					usage
 					exit 1
 				fi
+
 			elif [[ $1 == "-f" ]]
 			then
 				shift
 				if [[ -n $1 && $1 != \-* ]]
 				then
 					PROCFILE=$1
-					run_procfile
-					if [[ $? != 0 ]]
-                    then
-                        exit 1
-                    fi
 				else
 					usage
 					exit 1
@@ -73,132 +64,202 @@ function verify() {
 				exit 1
 			fi
 			shift
-		done
-	fi	
+		done	
+}
+
+
+#运行PROCFILE中的命令
+function run_command(){
+
+	load_env_file
+	run_procfile
+
+	i=0
+	while [[ $i -lt ${#PROCESS_COMMAND[@]} ]]
+    do
+    	eval ${PROCESS_COMMAND[$i]} &
+    	if [[ $? == 0 ]]
+    	then
+    		log $i $!
+    		tput clear 			#清除屏幕
+    	else
+    		echo "run error"
+    		exit 1
+    	fi
+
+    	if [[ ${PROCESS_COMMAND[$i]} =~ "PORT" ]]
+    	then
+    		let PORT++
+    		export PORT=$PORT
+    	fi
+    	let i++
+   	done
+
 }
 
 #打印日志
-function log() {
-    date=$(date +%H:%M:%S)
-    i=0
-    while [ $i -lt ${#PROCESS_NAME[@]} ]
-    do
-    	j=$[ $i % 3 ]
-    	case "$j" in
-    		"0")
-			strings="$BLUE""$date"" ""$PROCESS_NAME[$i]""  | ""$COLOR""$PROCESS_COMMAND[$i]"" start with pid "
-		;;
-			"1")
-			strings="$YELLOW""$date"" ""$PROCESS_NAME[$i]""  | ""$COLOR""$PROCESS_COMMAND[$i]"" start with pid "
-		;;
-			"2")
-			strings="$GREEN""$date"" ""$PROCESS_NAME[$i]""  | ""$COLOR""$PROCESS_COMMAND[$i]"" start with pid "
-		;;
-		esac
-		echo $strings
-    	let i++
-    done
+function log(){
+	date=$(date +%H:%M:%S)
+  	j=$[ $1 % 3 ]
+    case "$j" in
+    "0")
+		strings="$BLUE $date $PROCESS_NAME[$1] | $COLOR $PROCESS_COMMAND[$1] start with pid $2"
+	;;
+	"1")
+		strings="$YELLOW $date $PROCESS_NAME[$1]| $sCOLOR $PROCESS_COMMAND[$1] start with pid $2"
+	;;
+	"2")
+		strings="$GREEN $date $PROCESS_NAME[$1] | $COLOR $PROCESS_COMMAND[$1] start with pid $2"
+	;;
+	esac
+	echo $strings
 }
 
-#运行命令(运行procfile文件中全部命令)
-function run_command() {
-	
-    for command in ${PROCESS_COMMAND[@]}
-    do
-    	eval $command &
-
-    	if [[ $command =~ "$PORT" ]]
-    	then
-    		let PORT++
-    	fi
-    done
-}
-
-#检验并加载env文件
-function load_env_file() {
+#加载ENV_FILE文件
+function load_env_file(){
 	if [[ -e $ENV_FILE && -r $ENV_FILE ]]
 	then
-		cat $ENV_FILE | while read lines
+		while read lines
 		do	
-			if [[ -n $1 && $line == \#* ]]
+			if [[ -n $lines && $lines != \#* ]]
 			then
-				continue
-			fi
-
-			if [[ -n $1 && $line =~ "=" ]]
-			then
-				name=${line%=*}
-				content=${line#*=}
-				str=`echo $name | grep "[^0-9a-zA-Z_]"`
-				result=$?
-
-				if [[ $result == 1 && -n $content && !($content =~ " ") ]]
-				then 
-					eval export $line
-					if $? != 0
-					then
-						echo "ENV_FILE ERROR : $line"
-					fi
+				export $lines
+				if [[ $? != 0 ]]
+				then
+					echo "ENV_FILE ERROR : $lines"
+					exit 1
 				fi
-			else
-				echo "ENV_FILE ERROR : $line"
 			fi
-		done
+		done < $ENV_FILE
 	fi
 }
 
-#检验并执行procfile文件
-function run_procfile() {
-	if [[ -e "$PROCFILE" && -r "$PROCFILE" ]]
-    	then
-    	num=0
-        cat $PROCFILE | while read line
-        do
-        	if [[ -n $line && $line == \#* ]]
-			then
-				continue
-			fi
 
-			if [[ -n $line && $line =~ ":" ]]
+#检验ENV_FILE文件格式
+function check_env_file(){
+	is_env_true=0
+
+	if [[ -e $ENV_FILE && -r $ENV_FILE ]]
+	then
+		while read lines
+		do	
+			if [[ -n $lines ]]
 			then
-				command=${line#*:}
-				name=${line%:*}
+
+				if [[ $lines == \#* ]]
+				then
+					continue
+				fi
+
+				if [[ $lines =~ "=" ]]
+				then
+					name=${lines%=*}
+					content=${lines#*=}
+					str=`echo $name | grep "[^0-9a-zA-Z_]"`
+					result=$?
+
+					if [[ $result == 0 || -z $content || $content =~ " " ]]
+					then 
+						echo "ENV_FILE ERROR : $lines"
+						is_env_true=1		
+					fi
+				else
+						echo "ENV_FILE ERROR : $lines"
+						is_env_true=1
+				fi
+			fi
+		done < $ENV_FILE
+	else
+		echo "ENV_FILE ERROR : file error"
+		is_env_true=1
+	fi
+
+	return $is_env_true
+}
+
+#加载PROCFILE文件内容
+function run_procfile() {
+	if [[ -e $PROCFILE && -r $PROCFILE ]]
+    then
+    	num=0
+    	while read lines
+		do
+			if [[ -n $lines && $lines != \#* ]]
+			then	
+					PROCESS_NAME[num]=${lines%:*}
+					PROCESS_COMMAND[num]=${lines#*:}
+					let num++
+			fi
+		done < $PROCFILE
+	fi
+}
+
+
+#检验PROCFILE文件的格式
+function check_procfile_file(){
+	is_proc_true=0
+
+	if [[ -e $PROCFILE && -r $PROCFILE ]]
+    then
+        while read lines
+        do
+        	if [[ -n $lines ]]
+        	then
+        		if [[ $lines == \#* ]]
+				then
+					continue
+				fi
+
+				command=${lines#*:}
+				name=${lines%:*}
 				str=`echo $name | grep "[^0-9a-zA-Z_]"`
 				result=$?
 
- 				if [[ $result == 1  && -n $command ]]
+ 				if [[ $result == 0  || -z $command || ${lines: -1} == "&" ]]
             	then
-					PROCESS_NAME[num]=$name
-					PROCESS_COMMAND[num]=$command
-					if [[ ${line: -1} == "&" ]]
-					then
-						len=`expr ${#line} - 1`
-						PROCESS_COMMAND[num]=${line:0:$len}
-					fi
-					let num++
-           	 	else
-					echo "PROCFILE ERROR : $line"
+            		echo "PROCFILE ERROR : $lines"
+					is_proc_true=1
             	fi
-            else
-            	echo "PROCFILE ERROR : $line"
-            fi
-        done
-    fi
+			fi
+        done < $PROCFILE
+    else
+			echo "PROCFILE ERROR : file error"
+			is_proc_true=1
+	fi
+
+	return $is_proc_true
 }
 
 #接收SIGINT和SIGTERM信号并进行处理
 function handle_signal() {
-	process=""
-	for i in $process
+	run_process=`jobs -l`
+	for i in ${run_process[@]}
 	do
-		echo "kill the process [$i]"
 		kill -9 $i
 	done
 }
 
+
 function main() {
  	verify "$@"
 
+ 	if [[ $isCheck == 1 ]]
+ 	then
+ 		check_env_file
+ 		env_result=$?
+
+ 		check_procfile_file
+ 		procfile_result=$?
+
+ 		if [[ $env_result == 1 || $procfile_result == 1 ]]
+ 		then
+ 			exit 1
+ 		fi
+ 	fi
+
+ 	run_command	
+ 	wait
+ 	exit 0
 }
 
 main "$@"
